# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
    ]
