# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170725_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='The slug will be used as URL of the page. Must be unique!', max_length=200, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.ManyToManyField(blank=True, to='gallery.GalleryCategory'),
        ),
    ]
