# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170725_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='sorting_value',
            field=models.IntegerField(default=0),
        ),
    ]
