# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 22:42
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallerycategory_sorting_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='featured',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=''),
        ),
    ]
