# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 17:40
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_gallery_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='featured',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='featured'),
        ),
    ]
