# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20170815_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
