# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=160)),
            ],
        ),
    ]
