# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('domain', models.URLField()),
                ('description', models.CharField(max_length=160)),
                ('homepage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Homepage')),
            ],
        ),
    ]
