# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170724_2113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slide',
            new_name='CarouselSlide',
        ),
    ]
