# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20170724_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageSectionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='name',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='carousel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Carousel'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='contents',
            field=models.ManyToManyField(to='cms.HomepageSectionContent'),
        ),
    ]
