# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20170724_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sections',
            field=models.ManyToManyField(to='cms.HomepageSection'),
        ),
    ]
