# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20170724_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesectioncontent',
            options={'ordering': ('sorting_value',)},
        ),
    ]
