# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20170724_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesectioncontent',
            options={'ordering': ['sorting_value']},
        ),
    ]
