# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20170724_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesectioncontent',
            options={'get_latest_by': 'sorting_value'},
        ),
    ]
