# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 21:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20170724_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title visible in the browser and in search engine results.', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='The slug will be used as URL of the page. Must be unique!', max_length=200, unique=True, verbose_name='URL Slug')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 7, 24, 21, 48, 29, 284180, tzinfo=utc), verbose_name='date published')),
                ('short_description', models.CharField(help_text='Short description of the page.', max_length=200, verbose_name='Short description')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Main page content displayed in rich text.', null=True, verbose_name='Content')),
                ('menu_enabled', models.BooleanField(default=False, help_text='Enabling will add page to website menu.', verbose_name='Show in menu')),
                ('noindex', models.BooleanField(default=False, help_text='Enable to tell search engine robots to not index this page.', verbose_name="Don't index this page")),
                ('sorting_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='homepagesectioncontent',
            options={},
        ),
    ]
