# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20170724_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='short_description',
            new_name='description',
        ),
    ]
