# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20170725_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('page_items', models.ManyToManyField(blank=True, null=True, to='cms.Page')),
            ],
        ),
    ]
