# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
    ]
