# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_remove_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='sections',
            field=models.ManyToManyField(blank=True, to='cms.HomepageSection'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='contents',
            field=models.ManyToManyField(blank=True, to='cms.HomepageSectionContent'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page_items',
            field=models.ManyToManyField(blank=True, to='cms.Page'),
        ),
    ]
