# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20170725_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='menu_enabled',
        ),
    ]
