# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_remove_page_menu_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesectioncontent',
            name='button_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='homepagesectioncontent',
            name='button_text',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
