# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_sitefooter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='text',
            field=models.TextField(),
        ),
    ]
