# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_homepagesectioncontent_text_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesectioncontent',
            name='button_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=6),
        ),
    ]
