# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_homepagesectioncontent_button_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesectioncontent',
            name='offset',
            field=models.IntegerField(default=0),
        ),
    ]
