# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_homepagesectioncontent_offset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesection',
            options={'ordering': ['sorting_value']},
        ),
        migrations.AlterModelOptions(
            name='homepagesectioncontent',
            options={'ordering': ['sorting_value']},
        ),
    ]
