# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_websiteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfig',
            name='homepage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Homepage'),
        ),
        migrations.AlterField(
            model_name='websiteconfig',
            name='site_title',
            field=models.CharField(default='Django website', max_length=200),
        ),
    ]
