# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20171005_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
