# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20171005_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='created_date',
        ),
    ]
