# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Provide name for your upload.', max_length=200, verbose_name='Title')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Uploads',
            },
        ),
        migrations.CreateModel(
            name='UploadCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Provide category name.', max_length=200, verbose_name='Name')),
                ('short_description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Uploads - categories',
            },
        ),
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='uploads.UploadCategory'),
        ),
    ]
