# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='category',
            field=models.ManyToManyField(blank=True, to='uploads.UploadCategory'),
        ),
    ]
